### ISSUE TITLE
Plantillas ppt para Profesores

### ISSUE THREAD

**Issue by fabiangiraldousa** [fabiangiraldousa/centroCapacitaci-n#1]
Plantillas ppt para Profesores.  Revisar formato DataCamp: 
       https://www.datacamp.com/

**Comment by Morikatiando2020** [comment]
Adjunto plantilla, aun esta por definir el logo final.

[Plantilla_2020_ cursos_web.zip](https://github.com/fabiangiraldousa/centroCapacitaci-n/files/3945600/Plantilla_2020_.cursos_web.zip)

**Comment by Morikatiando2020** [comment]
Adjunto plantilla, aun esta por definir el logo final.
[Plantilla_2020_ cursos_web.zip](https://github.com/fabiangiraldousa/centroCapacitaci-n/files/3945734/Plantilla_2020_.cursos_web.zip)

**Comment by Morikatiando2020** [comment]
Adjunto plantilla 2020
[Plantilla_2020_ cursos_web.pptx](https://github.com/fabiangiraldousa/centroCapacitaci-n/files/3989197/Plantilla_2020_.cursos_web.pptx)

**Comment by Morikatiando2020** [comment]
[Plantilla_2020_ cursos_web.pptx](https://github.com/fabiangiraldousa/centroCapacitaci-n/files/3989204/Plantilla_2020_.cursos_web.pptx)

**Comment by Morikatiando2020** [comment]
[Plantilla_2020_.cursos_web.potx.zip](https://github.com/fabiangiraldousa/centroCapacitaci-n/files/3989218/Plantilla_2020_.cursos_web.potx.zip)
