### ISSUE TITLE
Revisión y control de calidad de Videos disponibles

### ISSUE THREAD

**Issue by fabiangiraldousa** [fabiangiraldousa/centroCapacitaci-n#5]
Revisión de Cursos Desarrollados.
   Linux. 
   Python
   Java.
   Competencias Blandas.

Definir formato de Reporte de Errores.

**Comment by Morikatiando2020** [comment]
Buen día, Adjunto XLSX Con la información solicitada( Revisión diseño, Java y Linux). Feliz Dia

[CONTROL DE VIDEOS.xlsx](https://github.com/fabiangiraldousa/centroCapacitaci-n/files/3951438/CONTROL.DE.VIDEOS.xlsx)
